cluster_name = "local-cluster"
location = "local-1"
server_id = 1
local_deployment = true
summary_filepath = "../benchmarks/logs/local-run/client-1.json"
output_filepath = "../benchmarks/logs/local-run/client-1.csv"
seed = 9

[request_config]
duration_sec = 60
requests_per_sec = 100
read_ratio = 0.0
key_range = [ 0, 39,]

[request_config.skew]
type = "Weighted"
weights = [ 300, 150, 60, 20, 10, 5, 5, 5, 5, 5,]
