cluster_name = "local-cluster"
location = "local-2"
server_id = 1 # the server to connect to
client_id = 2
local_deployment = true # use localhost
summary_filepath = "../benchmarks/logs/local-run/client-2.json"
output_filepath = "../benchmarks/logs/local-run/client-2.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[request_config]
duration_sec = 30
requests_per_sec = 100
read_ratio = 0.0
key_range = [0, 999]

[request_config.skew]
 type = "Weighted"
 weights = [ 60, 20, 10, 5, 5, 1, 1, 1, 1, 1,]
#type = "Uniform"
