location = "local-2"
server_id = 2
num_clients = 0
summary_filepath = "../benchmarks/logs/local-run/server-2.json"
output_filepath = "../benchmarks/logs/local-run/server-2.csv"
in_scheduling_strategy = "TargetedThroughput"
out_scheduling_strategy = "TargetedThroughput"
local_deployment = true
cluster_name = "local-cluster"
nodes = [ 1, 2, 3,]
initial_leader = 1
num_partitions = 40
partition_size = 1

[initial_flexible_quorum]
read_quorum_size = 2
write_quorum_size = 2
